---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-cm
  namespace: bggns
  labels:
    app: bgg
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local

---  
apiVersion: v1
kind: Secret
metadata:
  name: bggapp-secret
  namespace: bggns
  labels:
    app: bgg
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ= # Base64 for name from configmap