apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: test-ns
commonLabels:
  env: test
  dept: eng

replicas:
- name: dov-deploy
  count: 1

images:
- name: chukmunnlee/dov-bear
  newTag: v5