---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dov-cm
  namespace: myns
data:
  myconfig.conf: |
    Hello World
  readme.txt: this is a readonly directory

---
apiVersion: v1 # If its core, you can ommit, else core/v1
kind: Pod
metadata:
  name: dov-po # Resource name
  namespace: myns # Define namespace
  labels:
    app: dov
    env: dev
spec:
  volumes:
    - name: cm-vol
      configMap:
        name: dov-cm
  containers:
    - name: dov-container
      image: jianwei14/bear:1.0.0
      imagePullPolicy: IfNotPresent # Always, Never, IfNotPresent
      env: # environment variables
      - name: INSTANCE_NAME
        value: dov pod
      - name: INSTANCE_HASH
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['app']
      ports:
        - name: web-port
          containerPort: 3000
        - name: metrics-port
          containerPort: 3100
      livenessProbe:
        httpGet:
          path: /healthz
          port: web-port
        periodSeconds: 30
        initialDelaySeconds: 5
      volumeMounts:
        - mountPath: /opt
          name: cm-vol
          readOnly: true

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dov-ing
  namespace: myns
  labels:
    app: dov
    name: dov-ing
spec:
  ingressClassName: nginx
  rules:
    - host: dov-139.59.223.175.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dov-svc
                port:
                  name: svc-web-port
              
