---
apiVersion: v1 # If its core, you can ommit, else core/v1
kind: Pod
metadata:
  name: dov-po # Resource name
  namespace: myns # Define namespace
  labels:
    app: dov
    env: dev
spec:
  containers:
    - name: dov-container
      image: jianwei14/bear:1.0.0
      imagePullPolicy: IfNotPresent # Always, Never, IfNotPresent
      env: # environment variables
      - name: INSTANCE_NAME
        value: dov pod
      - name: INSTANCE_HASH
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['app']
      ports:
        - name: web-port
          containerPort: 3000
        - name: metrics-port
          containerPort: 3100
      livenessProbe:
        httpGet:
          path: /healthz
          port: web-port
        periodSeconds: 30
        initialDelaySeconds: 5

